apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
  namespace: "{{ .Values.site }}"
spec:
  # prettier-ignore
  replicas: {{ .Values.replica | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tracking
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracking
    spec:
      containers:
        - name: tracking
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: API_URL
              value: "{{ .Values.api.url }}"
            - name: VITE_APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_APP_TITLE
            - name: VITE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_VERSION
            - name: VITE_API_MAIN_PATH
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_API_MAIN_PATH
            - name: VITE_APP_BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_APP_BASE_PATH
            - name: VITE_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_API_ENDPOINT
            - name: VITE_KEYCLOAK_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_KEYCLOAK_BASE_URL
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_KEYCLOAK_REALM
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: tracking-config
                  key: VITE_KEYCLOAK_CLIENT_ID
            - name: VITE_KEYCLOAK_CLIENT_SECRET
              value: "{{ .Values.config.keycloak.clientSecret }}"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1024Mi
              cpu: 1000m
      imagePullSecrets:
        - name: regklynx
