apiVersion: v1
kind: Service
metadata:
  name: tracking
  namespace: "{{ .Values.site }}"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: tracking
  sessionAffinity: None
  type: ClusterIP
